version: "3.8"
services:
  ui:
    hostname: frontend
    image: martezr/puppet-demo-frontend
    ports:
      - "80:80"
    links:
      - nameservice
  nameservice:
    hostname: nameservice
    image: martezr/puppet-demo-name
    ports:
      - "8000:8000"
  passwordservice:
    hostname: passwordservice
    image: martezr/puppet-demo-password
    ports:
      - "8001:8001"