apiVersion: v1
kind: Namespace
metadata:
  name: puppetdemo
  annotations:
    kuma.io/sidecar-injection: enabled
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: puppetdemo
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: puppetdemo
  labels:
    app: frontend
    service: frontend-service
#  annotations:
#    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppet-frontend
  namespace: puppetdemo
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: martezr/puppet-demo-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nameservice
  namespace: puppetdemo
  labels:
    app: nameservice
    service: nameservice
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: nameservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppet-nameservice
  namespace: puppetdemo
  labels:
    app: nameservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nameservice
  template:
    metadata:
      labels:
        app: nameservice
    spec:
      containers:
      - name: nameservice
        image: martezr/puppet-demo-name
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: passwordservice
  namespace: puppetdemo
  labels:
    app: passwordservice
    service: passwordservice
spec:
  ports:
  - port: 8001
    name: http
  selector:
    app: passwordservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppet-passwordservice
  namespace: puppetdemo
  labels:
    app: passwordservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwordservice
  template:
    metadata:
      labels:
        app: passwordservice
    spec:
      containers:
      - name: passwordservice
        image: martezr/puppet-demo-password
        ports:
        - containerPort: 8001